# Generated by Django 2.1.7 on 2019-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictionlisting',
            fields=[
                ('commitid', models.CharField(db_column='CommitId', max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='TimeStamp')),
                ('prediction', models.CharField(db_column='Prediction', max_length=50)),
                ('filename', models.CharField(db_column='FileName', max_length=50)),
                ('filelink', models.CharField(db_column='FileLink', max_length=50)),
            ],
            options={
                'db_table': 'predictionlisting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('projectname', models.CharField(db_column='ProjectName', max_length=50)),
                ('codinglanguage', models.CharField(db_column='CodingLanguage', max_length=50)),
                ('totalfilesforprediction', models.CharField(db_column='TotalFilesForPrediction', max_length=50)),
                ('totalcommitsforprediction', models.CharField(db_column='TotalCommitsForPrediction', max_length=50)),
                ('buggypredictions', models.CharField(db_column='BuggyPredictions', max_length=50)),
                ('predictionsincedays', models.CharField(db_column='PredictionSinceDays', max_length=50)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
    ]
