# Generated by Django 2.1.7 on 2019-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectsummary',
            fields=[
                ('id', models.PositiveIntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('totalfilesforprediction', models.IntegerField(db_column='TotalFilesForPrediction')),
                ('totalcommitsforprediction', models.IntegerField(db_column='TotalCommitsForPrediction')),
                ('buggypredictions', models.IntegerField(db_column='BuggyPredictions')),
            ],
            options={
                'db_table': 'projectsummary',
                'managed': False,
            },
        ),
    ]
