# Generated by Django 2.1.7 on 2019-06-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projectsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explainablecdp',
            fields=[
                ('explainablecdpid', models.AutoField(db_column='ExplainableCDPId', primary_key=True, serialize=False)),
                ('featurename', models.CharField(blank=True, db_column='FeatureName', max_length=50, null=True)),
                ('featurekey', models.CharField(blank=True, db_column='FeatureKey', max_length=50, null=True)),
                ('featurevalue', models.FloatField(blank=True, db_column='FeatureValue', null=True)),
                ('featureunits', models.CharField(blank=True, db_column='FeatureUnits', max_length=10, null=True)),
                ('featurelabel', models.IntegerField(db_column='FeatureLabel')),
                ('featurecoefficient', models.FloatField(blank=True, db_column='FeatureCoefficient', null=True)),
                ('createtimestamp', models.DateTimeField(db_column='CreateTimestamp')),
            ],
            options={
                'db_table': 'explainablecdp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predctionfeaturetrend',
            fields=[
                ('featuretrendid', models.AutoField(db_column='FeatureTrendId', primary_key=True, serialize=False)),
                ('featurename', models.CharField(db_column='FeatureName', max_length=50)),
                ('median', models.FloatField()),
                ('firstquartile', models.FloatField(db_column='firstQuartile')),
                ('thirdquartile', models.FloatField(db_column='thirdQuartile')),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('prediction', models.IntegerField(db_column='Prediction')),
                ('createtime', models.DateTimeField(db_column='CreateTime')),
            ],
            options={
                'db_table': 'predctionfeaturetrend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predictionrawdata',
            fields=[
                ('predictionrawdataid', models.AutoField(db_column='PredictionRawDataId', primary_key=True, serialize=False)),
                ('day', models.DateField(db_column='DAY')),
                ('raw_data', models.TextField(blank=True, db_column='RAW_DATA', null=True)),
                ('timestamp', models.DateTimeField(db_column='TIMESTAMP')),
            ],
            options={
                'db_table': 'predictionrawdata',
                'managed': False,
            },
        ),
    ]
